name: flutter_base
description: NAME DESCRIPTION HERE

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

#SCRIPT
scripts:
  # RUN THIS SCRIPT:  dart pub global activate rps --version 0.8.0
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  gen: "fvm flutter pub run easy_localization:generate -S assets/locale -f keys -o locale_keys.g.dart && fvm flutter pub run build_runner watch -d"
  # run generate localizations
  localization: "fvm flutter pub run easy_localization:generate -S assets/locale -f keys -o locale_keys.g.dart"
  # pub get -> generate localization -> run build_runner
  get: "fvm flutter pub get && fvm flutter pub run easy_localization:generate -S assets/locale -f keys -o locale_keys.g.dart && fvm flutter pub run build_runner watch -d"
  # format after pushing
  format: "dart format"
  # pub clean -> pub get -> generate localization -> run build_runner
  refresh: "fvm flutter clean && fvm flutter pub get && fvm flutter pub run easy_localization:generate -S lib/app/locale/translations -f keys -o locale_keys.g.dart && fvm flutter pub run build_runner watch -d"

# Config flutter gen
flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_sgv: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  bloc_concurrency: ^0.2.3
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.4
  permission_handler: ^11.3.1
  animated_text_kit: ^4.2.2
  animations: ^2.0.10
  shimmer: ^3.0.0
  flutter_blurhash: ^0.8.2
  dio: ^5.4.0
  logger: ^2.0.2+1 
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  get_it: ^7.6.4
  easy_localization: ^3.0.3

  flutter_svg: ^2.0.9
  injectable: ^2.3.2
  image: ^4.1.3
  lottie: ^2.7.0
  transparent_image: ^2.0.1
  retrofit: ^4.0.3
  package_info: ^2.0.2
  package_info_plus: ^3.1.2
  awesome_dio_interceptor: ^1.0.0
  vector_math: ^2.1.4
  talker_bloc_logger: ^2.4.0
  rps: ^0.7.0
  hydrated_bloc: ^9.1.3
  replay_bloc: ^0.2.5
  path_provider: ^2.1.2
  rive: ^0.13.7
  calendar_view: ^1.2.0
  syncfusion_flutter_calendar: ^26.1.35
  dio_smart_retry: ^6.0.0
  firebase_core: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
  bloc_test: ^9.1.5
  auto_route_generator: ^7.3.2
  retrofit_generator: '>=8.0.6'

  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/locale/
    - assets/env/
    - assets/gif/
    - assets/riv/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Clash Grotesk
      fonts:
        - asset: assets/fonts/ClashGrotesk-Regular.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
