name: flutter_base
description: NAME DESCRIPTION HERE

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.19.4 <4.0.0"

#SCRIPT
scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  gen: "fvm flutter pub run easy_localization:generate -S assets/locale -f keys -o locale_keys.g.dart && fvm flutter pub run build_runner watch -d"
  # run generate localizations
  localization: "fvm flutter pub run easy_localization:generate -S assets/locale -f keys -o locale_keys.g.dart"
  # pub get -> generate localization -> run build_runner
  get: "fvm flutter pub get && fvm flutter pub run easy_localization:generate -S assets/locale -f keys -o locale_keys.g.dart && fvm flutter pub run build_runner watch -d"
  # format after pushing
  format: "dart format"
  # pub clean -> pub get -> generate localization -> run build_runner
  refresh: "fvm flutter clean && fvm flutter pub get && fvm flutter pub run easy_localization:generate -S lib/app/locale/translations -f keys -o locale_keys.g.dart && fvm flutter pub run build_runner watch -d"

# Config flutter gen
flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_sgv: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  bloc_concurrency: ^0.2.1
  freezed_annotation: ^2.2.0
  auto_route: ^6.0.0+1
  permission_handler: ^10.2.0
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  shimmer: ^2.0.0
  flutter_blurhash: ^0.7.0
  dio: ^5.0.3
  logger: ^1.3.0
  dotenv: ^4.1.0
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  flutter_exif_rotation: ^0.5.1

  flutter_svg: ^2.0.4
  injectable: ^2.1.1
  image: ^4.0.15
  lottie: ^2.3.1
  transparent_image: ^2.0.1
  retrofit: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info: ^2.0.2
  package_info_plus: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.2.0
  bloc_test: ^9.1.1
  auto_route_generator: ^6.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/locale/
    - assets/env/
    - assets/gif/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
